const colours = {};

colours.colourMeaning = { //holds values for fortune at end
    red: `<p>People with red auras cut a winding and far-ranging path though life, gathering stories like souvenirs along the way. You are innately curious, but have a tendency to lose interest quickly. Some red auras leave a trail of broken hearts and unkept promises in their wake. But when you put your mind to it, you can move mountains.</p>`,
    orange: `<p>People with orange auras are the beating heart of any gathering. You are gregarious, generous, good-hearted, and kind. You love to be around people, whether you are the centre of attention or just another face in the crowd. People are at ease in your presence. People with orange auras live successful and happy lives.</p>`,
    yellow: `<p>People with yellow auras are independent, logical, whip-smart, and delightfully eccentric. You read people quickly and with stunning accuracy. You don’t suffer fools, but you are the first to recognize brilliance in others. You are an unorthodox and unconventional thinker.</p>`,
    green: `<p>People with green auras have their head in the clouds and their feet on the ground. Your creativity finds expression in down-to-earth pursuits such as gardening, cooking, or crafts. You love to work with your hands, and your home is a haven. You are generous and loyal. You like security and stability in your life. You are well-attuned to nature.</p>`,
    blue: `<p>The blue aura is very rare. People with blue auras are eloquent and charismatic. You are a born leader. You command respect through your competence, patience, and authoritative presence. Your head and heart play equal roles when you make important decisions.</p>`,
    turquoise: `<p>People with turquoise auras are healers. You are sensitive, compassionate, and an excellent listener. You are steady and unflappable. You see the potential in those around you, and you thrive on lending your courage and wisdom in support of your loved ones.</p>`,
    purple: `<p>People with purple auras are philosophical, inquiring and intuitive. You have bottomless curiosity and love to learn. You keep a small and tight group of friends, but your warmth and enthusiasm for sharing your interests are widely admired. Animals love you.</p>`,
    white: `<p>People with white auras are exceptionally gifted. Your life lesson is to discover how to use your gifts wisely. You are sensitive, and able to use your spiritual intuition in practical ways. You are versatile and adaptable, and naturally reflect your surroundings and the people around you. Success comes easily to you.</p>`,
};
