const colours = {}

colours.colourMeaning = { //holds values for fortune at end
    red: `<p>People with red auras cut a winding and far-ranging path though life, gathering stories like souveniers along the way. You are innately curious, but you also have a tendancy to lose interest quickly. Some red auras leave a trail of broken hearts and unkept promises in their wake. (Not to mention a metaphoroical closet filled with unfinished projects.)</p><p class="profile">When you put your mind to it, you can move mountains.</p>`,
    orange: `<p>People with orange auras are the beating heart of any gathering. You are gragarious, generous, good-hearted, and kind. You love to be around people, whether you are the center of attention or just another face in the crowd. And people love to be around you too, because you put them at ease.</p><p class="profile">People with orange auras live successful and happy lives.</p>`,
    yellow: `<p>People with yellow auras are independant, logical, and whip-smart. You read people quickly and with stunning accuracy. You don't suffer fools, but you are the first to recognize brilliance in others. Your sharp insight can give you a tendancy to be critical of yourself, but you are as brilliant as they come, and deep down you know that too. You are an unorthodox and unconventional thinker.</p><p class="profile">Many yellow auras are delightfully eccentric. </p>`,
    green: `<p>People with green auras have their head in the clouds and their feet on the ground. Your significant creativity finds expression in down to earth persuits: gardening, cooking, crafts. You love to work with your hands, and your home is a haven. You are generous and loyal and well-deserving of the admiration and respect you attract. You like security and stability in your life. You are well-attuned to nature.</p>`,
    blue: `<p>The blue aura is very rare. People with blue auras are elequent and charismatic. You are a born leader. You command respect through your competience, patience, and authoritative presence. Your head and heart play equal roles whe you make important decisions.</p>`,
    turquoise: `<p>People with turquise auras are healers. You are sensitive, compassionate, and an excellent listener. You are steady and unflappable. You see the potential in those around you, and you thrive on lending some of your significant courage and wisdom in support of other's personal development.</p>`,
    purple: `<p>People with purple auras are philosophical, inquiring and intuitive. You have a bottomless curiousity and love to learn. You keep a small and tight group of friends, but your warmth and enthusism for sharing your interests make you very well-liked. Animals love you.</p>`,
    white: `<p>People with white auras are exceptionally gifted. Your life lesson is to discover how to use your gifts wisely. You are sensitve and intuitive, and able to use your spiritual intuition in practical ways. You are versitle and adaptable, and naturally reflext your surroundings and the people around you. You are highly intellectual. You are able to make the correct decision and follow through. Success comes easily to you.</p>`,
}