colours.prompts = [
    `Think of a question you would like to ask someone who remembers you as a child.`,
    `Think of a stranger who was kind to you.`,
    `Think of a time you were kind to a stranger.`,
    `What scares you?`,
    `Think of something that no one knows about you.`,
    `What are you looking forward to?`,
    `What would you do if you weren't afraid?`,
    `Think of a fictional character who feels real to you.`,
    `What is the first thing you remember?`,
    `Remember a time when you were lost.`,
    `When did you feel truly independent for the first time?`,
    `What would you do if you knew you could not fail?`,
    `What do you need to forgive yourself for?`,
    `If you could go back in time to change one thing, what would it be?`,
    `What's the most daring thing you've ever done?`,
    `Which of your five senses is the strongest?`,
    `Who knows you best?`,
    `What keeps you up at night?`,
    `What lie do you tell most often?`,
    `What do you regret not doing?`,
    `What gives your life meaning?`,
    `Think of a bridge your burnt.`,
    `What do people see when they look at you?`,
]