colours.twitter = { //holds values for twitter share button
    red: `<a href="https://twitter.com/intent/tweet?text=My%20aura%20is%20red.%20Discover%20your%20aura%20at%20http://www.carolynmcneillie.com/colours%20pic.twitter.com/LsRIoIwNwc%20@carolynalive" target="_blank"><span class="fa fa-twitter"></span></a>`,
    orange: `<a href="https://twitter.com/intent/tweet?text=My%20aura%20is%20orange.%20Discover%20your%20aura%20at%20http://www.carolynmcneillie.com/colours%20pic.twitter.com/QjX2TmszBs%20@carolynalive" target="_blank"><span class="fa fa-twitter"></span></a>`,
    yellow: `<a href="https://twitter.com/intent/tweet?text=My%20aura%20is%20yellow.%20Discover%20your%20aura%20at%20http://www.carolynmcneillie.com/colours%20pic.twitter.com/gC7Q1JasuB%20@carolynalive" target="_blank"><span class="fa fa-twitter"></span></a>`,
    green: `<a href="https://twitter.com/intent/tweet?text=My%20aura%20is%20green.%20Discover%20your%20aura%20at%20http://www.carolynmcneillie.com/colours%20pic.twitter.com/VVSW077KeS%20@carolynalive" target="_blank"><span class="fa fa-twitter"></span></a>`,
    turquoise: `<a href="https://twitter.com/intent/tweet?text=My%20aura%20is%20turquoise.%20Discover%20your%20aura%20at%20http://www.carolynmcneillie.com/colours%20pic.twitter.com/xquJo2Bguo%20@carolynalive" target="_blank"><span class="fa fa-twitter"></span></a>`,
    blue: `<a href="https://twitter.com/intent/tweet?text=My%20aura%20is%20blue.%20Discover%20your%20aura%20at%20http://www.carolynmcneillie.com/colours%20pic.twitter.com/E3SdsiIqPr%20@carolynalive" target="_blank"><span class="fa fa-twitter"></span></a>`,
    purple: `<a href="https://twitter.com/intent/tweet?text=My%20aura%20is%20purple.%20Discover%20your%20aura%20at%20http://www.carolynmcneillie.com/colours%20pic.twitter.com/QXHwHt5FDR%20@carolynalive" target="_blank"><span class="fa fa-twitter"></span></a>`,
    white: `<a href="https://twitter.com/intent/tweet?text=My%20aura%20is%20white.%20Discover%20your%20aura%20at%20http://www.carolynmcneillie.com/colours%20pic.twitter.com/GUiMBELTqK%20@carolynalive" target="_blank"><span class="fa fa-twitter"></span></a>`,
};
